# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /mnt/Texas/prj/ue5
GAMEPROJECTFILE =/home/mika/prj/KitchenSink/KitchenSink.uproject

TARGETS = \
	KitchenSink-Linux-Debug  \
	KitchenSink-Linux-DebugGame  \
	KitchenSink-Linux-Test  \
	KitchenSink-Linux-Shipping  \
	KitchenSink \
	KitchenSinkEditor-Linux-Debug  \
	KitchenSinkEditor-Linux-DebugGame  \
	KitchenSinkEditor-Linux-Test  \
	KitchenSinkEditor-Linux-Shipping  \
	KitchenSinkEditor \
	BaseTextureBuildWorker-Linux-Debug  \
	BaseTextureBuildWorker-Linux-DebugGame  \
	BaseTextureBuildWorker-Linux-Test  \
	BaseTextureBuildWorker-Linux-Shipping  \
	BaseTextureBuildWorker \
	BenchmarkTool-Linux-Debug  \
	BenchmarkTool-Linux-DebugGame  \
	BenchmarkTool-Linux-Test  \
	BenchmarkTool-Linux-Shipping  \
	BenchmarkTool \
	BlankProgram-Linux-Debug  \
	BlankProgram-Linux-DebugGame  \
	BlankProgram-Linux-Test  \
	BlankProgram-Linux-Shipping  \
	BlankProgram \
	BuildPatchTool-Linux-Debug  \
	BuildPatchTool-Linux-DebugGame  \
	BuildPatchTool-Linux-Test  \
	BuildPatchTool-Linux-Shipping  \
	BuildPatchTool \
	ChaosUserDataPTTests-Linux-Debug  \
	ChaosUserDataPTTests-Linux-DebugGame  \
	ChaosUserDataPTTests-Linux-Test  \
	ChaosUserDataPTTests-Linux-Shipping  \
	ChaosUserDataPTTests \
	ChaosVisualDebugger-Linux-Debug  \
	ChaosVisualDebugger-Linux-DebugGame  \
	ChaosVisualDebugger-Linux-Test  \
	ChaosVisualDebugger-Linux-Shipping  \
	ChaosVisualDebugger \
	CrashReportClient-Linux-Debug  \
	CrashReportClient-Linux-DebugGame  \
	CrashReportClient-Linux-Test  \
	CrashReportClient-Linux-Shipping  \
	CrashReportClient \
	CrashReportClientEditor-Linux-Debug  \
	CrashReportClientEditor-Linux-DebugGame  \
	CrashReportClientEditor-Linux-Test  \
	CrashReportClientEditor-Linux-Shipping  \
	CrashReportClientEditor \
	DatasmithUE4ArchiCAD-Linux-Debug  \
	DatasmithUE4ArchiCAD-Linux-DebugGame  \
	DatasmithUE4ArchiCAD-Linux-Test  \
	DatasmithUE4ArchiCAD-Linux-Shipping  \
	DatasmithUE4ArchiCAD \
	DatasmithArchiCAD-Linux-Debug  \
	DatasmithArchiCAD-Linux-DebugGame  \
	DatasmithArchiCAD-Linux-Test  \
	DatasmithArchiCAD-Linux-Shipping  \
	DatasmithArchiCAD \
	DatasmithCADWorker-Linux-Debug  \
	DatasmithCADWorker-Linux-DebugGame  \
	DatasmithCADWorker-Linux-Test  \
	DatasmithCADWorker-Linux-Shipping  \
	DatasmithCADWorker \
	DatasmithFacadeCSharp-Linux-Debug  \
	DatasmithFacadeCSharp-Linux-DebugGame  \
	DatasmithFacadeCSharp-Linux-Test  \
	DatasmithFacadeCSharp-Linux-Shipping  \
	DatasmithFacadeCSharp \
	DatasmithMax2016-Linux-Debug  \
	DatasmithMax2016-Linux-DebugGame  \
	DatasmithMax2016-Linux-Test  \
	DatasmithMax2016-Linux-Shipping  \
	DatasmithMax2016 \
	DatasmithMax2017-Linux-Debug  \
	DatasmithMax2017-Linux-DebugGame  \
	DatasmithMax2017-Linux-Test  \
	DatasmithMax2017-Linux-Shipping  \
	DatasmithMax2017 \
	DatasmithMax2018-Linux-Debug  \
	DatasmithMax2018-Linux-DebugGame  \
	DatasmithMax2018-Linux-Test  \
	DatasmithMax2018-Linux-Shipping  \
	DatasmithMax2018 \
	DatasmithMax2019-Linux-Debug  \
	DatasmithMax2019-Linux-DebugGame  \
	DatasmithMax2019-Linux-Test  \
	DatasmithMax2019-Linux-Shipping  \
	DatasmithMax2019 \
	DatasmithMax2020-Linux-Debug  \
	DatasmithMax2020-Linux-DebugGame  \
	DatasmithMax2020-Linux-Test  \
	DatasmithMax2020-Linux-Shipping  \
	DatasmithMax2020 \
	DatasmithMax2021-Linux-Debug  \
	DatasmithMax2021-Linux-DebugGame  \
	DatasmithMax2021-Linux-Test  \
	DatasmithMax2021-Linux-Shipping  \
	DatasmithMax2021 \
	DatasmithMax2022-Linux-Debug  \
	DatasmithMax2022-Linux-DebugGame  \
	DatasmithMax2022-Linux-Test  \
	DatasmithMax2022-Linux-Shipping  \
	DatasmithMax2022 \
	DatasmithMax2023-Linux-Debug  \
	DatasmithMax2023-Linux-DebugGame  \
	DatasmithMax2023-Linux-Test  \
	DatasmithMax2023-Linux-Shipping  \
	DatasmithMax2023 \
	DatasmithNavisworks2019-Linux-Debug  \
	DatasmithNavisworks2019-Linux-DebugGame  \
	DatasmithNavisworks2019-Linux-Test  \
	DatasmithNavisworks2019-Linux-Shipping  \
	DatasmithNavisworks2019 \
	DatasmithNavisworks2020-Linux-Debug  \
	DatasmithNavisworks2020-Linux-DebugGame  \
	DatasmithNavisworks2020-Linux-Test  \
	DatasmithNavisworks2020-Linux-Shipping  \
	DatasmithNavisworks2020 \
	DatasmithNavisworks2021-Linux-Debug  \
	DatasmithNavisworks2021-Linux-DebugGame  \
	DatasmithNavisworks2021-Linux-Test  \
	DatasmithNavisworks2021-Linux-Shipping  \
	DatasmithNavisworks2021 \
	DatasmithNavisworks2022-Linux-Debug  \
	DatasmithNavisworks2022-Linux-DebugGame  \
	DatasmithNavisworks2022-Linux-Test  \
	DatasmithNavisworks2022-Linux-Shipping  \
	DatasmithNavisworks2022 \
	DatasmithNavisworks2023-Linux-Debug  \
	DatasmithNavisworks2023-Linux-DebugGame  \
	DatasmithNavisworks2023-Linux-Test  \
	DatasmithNavisworks2023-Linux-Shipping  \
	DatasmithNavisworks2023 \
	DatasmithRevit2018-Linux-Debug  \
	DatasmithRevit2018-Linux-DebugGame  \
	DatasmithRevit2018-Linux-Test  \
	DatasmithRevit2018-Linux-Shipping  \
	DatasmithRevit2018 \
	DatasmithRevit2019-Linux-Debug  \
	DatasmithRevit2019-Linux-DebugGame  \
	DatasmithRevit2019-Linux-Test  \
	DatasmithRevit2019-Linux-Shipping  \
	DatasmithRevit2019 \
	DatasmithRevit2020-Linux-Debug  \
	DatasmithRevit2020-Linux-DebugGame  \
	DatasmithRevit2020-Linux-Test  \
	DatasmithRevit2020-Linux-Shipping  \
	DatasmithRevit2020 \
	DatasmithRevit2021-Linux-Debug  \
	DatasmithRevit2021-Linux-DebugGame  \
	DatasmithRevit2021-Linux-Test  \
	DatasmithRevit2021-Linux-Shipping  \
	DatasmithRevit2021 \
	DatasmithRevit2022-Linux-Debug  \
	DatasmithRevit2022-Linux-DebugGame  \
	DatasmithRevit2022-Linux-Test  \
	DatasmithRevit2022-Linux-Shipping  \
	DatasmithRevit2022 \
	DatasmithRevit2023-Linux-Debug  \
	DatasmithRevit2023-Linux-DebugGame  \
	DatasmithRevit2023-Linux-Test  \
	DatasmithRevit2023-Linux-Shipping  \
	DatasmithRevit2023 \
	DatasmithRhino6-Linux-Debug  \
	DatasmithRhino6-Linux-DebugGame  \
	DatasmithRhino6-Linux-Test  \
	DatasmithRhino6-Linux-Shipping  \
	DatasmithRhino6 \
	DatasmithRhino7-Linux-Debug  \
	DatasmithRhino7-Linux-DebugGame  \
	DatasmithRhino7-Linux-Test  \
	DatasmithRhino7-Linux-Shipping  \
	DatasmithRhino7 \
	DatasmithSDK-Linux-Debug  \
	DatasmithSDK-Linux-DebugGame  \
	DatasmithSDK-Linux-Test  \
	DatasmithSDK-Linux-Shipping  \
	DatasmithSDK \
	DatasmithSketchUpRuby2019-Linux-Debug  \
	DatasmithSketchUpRuby2019-Linux-DebugGame  \
	DatasmithSketchUpRuby2019-Linux-Test  \
	DatasmithSketchUpRuby2019-Linux-Shipping  \
	DatasmithSketchUpRuby2019 \
	DatasmithSketchUpRuby2020-Linux-Debug  \
	DatasmithSketchUpRuby2020-Linux-DebugGame  \
	DatasmithSketchUpRuby2020-Linux-Test  \
	DatasmithSketchUpRuby2020-Linux-Shipping  \
	DatasmithSketchUpRuby2020 \
	DatasmithSketchUpRuby2021-Linux-Debug  \
	DatasmithSketchUpRuby2021-Linux-DebugGame  \
	DatasmithSketchUpRuby2021-Linux-Test  \
	DatasmithSketchUpRuby2021-Linux-Shipping  \
	DatasmithSketchUpRuby2021 \
	DatasmithSketchUpRuby2022-Linux-Debug  \
	DatasmithSketchUpRuby2022-Linux-DebugGame  \
	DatasmithSketchUpRuby2022-Linux-Test  \
	DatasmithSketchUpRuby2022-Linux-Shipping  \
	DatasmithSketchUpRuby2022 \
	DatasmithSolidworks2021-Linux-Debug  \
	DatasmithSolidworks2021-Linux-DebugGame  \
	DatasmithSolidworks2021-Linux-Test  \
	DatasmithSolidworks2021-Linux-Shipping  \
	DatasmithSolidworks2021 \
	EpicWebHelper-Linux-Debug  \
	EpicWebHelper-Linux-DebugGame  \
	EpicWebHelper-Linux-Test  \
	EpicWebHelper-Linux-Shipping  \
	EpicWebHelper \
	HeadlessChaos-Linux-Debug  \
	HeadlessChaos-Linux-DebugGame  \
	HeadlessChaos-Linux-Test  \
	HeadlessChaos-Linux-Shipping  \
	HeadlessChaos \
	HeadlessChaosPerf-Linux-Debug  \
	HeadlessChaosPerf-Linux-DebugGame  \
	HeadlessChaosPerf-Linux-Test  \
	HeadlessChaosPerf-Linux-Shipping  \
	HeadlessChaosPerf \
	InterchangeWorker-Linux-Debug  \
	InterchangeWorker-Linux-DebugGame  \
	InterchangeWorker-Linux-Test  \
	InterchangeWorker-Linux-Shipping  \
	InterchangeWorker \
	LiveCodingConsole-Linux-Debug  \
	LiveCodingConsole-Linux-DebugGame  \
	LiveCodingConsole-Linux-Test  \
	LiveCodingConsole-Linux-Shipping  \
	LiveCodingConsole \
	LowLevelTests-Linux-Debug  \
	LowLevelTests-Linux-DebugGame  \
	LowLevelTests-Linux-Test  \
	LowLevelTests-Linux-Shipping  \
	LowLevelTests \
	ReplicationSystemTest-Linux-Debug  \
	ReplicationSystemTest-Linux-DebugGame  \
	ReplicationSystemTest-Linux-Test  \
	ReplicationSystemTest-Linux-Shipping  \
	ReplicationSystemTest \
	ShaderCompileWorker-Linux-Debug  \
	ShaderCompileWorker-Linux-DebugGame  \
	ShaderCompileWorker-Linux-Test  \
	ShaderCompileWorker-Linux-Shipping  \
	ShaderCompileWorker \
	DotNetPerforceLib-Linux-Debug  \
	DotNetPerforceLib-Linux-DebugGame  \
	DotNetPerforceLib-Linux-Test  \
	DotNetPerforceLib-Linux-Shipping  \
	DotNetPerforceLib \
	SlateUGS-Linux-Debug  \
	SlateUGS-Linux-DebugGame  \
	SlateUGS-Linux-Test  \
	SlateUGS-Linux-Shipping  \
	SlateUGS \
	SlateViewer-Linux-Debug  \
	SlateViewer-Linux-DebugGame  \
	SlateViewer-Linux-Test  \
	SlateViewer-Linux-Shipping  \
	SlateViewer \
	SwitchboardListener-Linux-Debug  \
	SwitchboardListener-Linux-DebugGame  \
	SwitchboardListener-Linux-Test  \
	SwitchboardListener-Linux-Shipping  \
	SwitchboardListener \
	SymsLibDump-Linux-Debug  \
	SymsLibDump-Linux-DebugGame  \
	SymsLibDump-Linux-Test  \
	SymsLibDump-Linux-Shipping  \
	SymsLibDump \
	TestPAL-Linux-Debug  \
	TestPAL-Linux-DebugGame  \
	TestPAL-Linux-Test  \
	TestPAL-Linux-Shipping  \
	TestPAL \
	UnrealFrontend-Linux-Debug  \
	UnrealFrontend-Linux-DebugGame  \
	UnrealFrontend-Linux-Test  \
	UnrealFrontend-Linux-Shipping  \
	UnrealFrontend \
	UnrealHeaderTool-Linux-Debug  \
	UnrealHeaderTool-Linux-DebugGame  \
	UnrealHeaderTool-Linux-Test  \
	UnrealHeaderTool-Linux-Shipping  \
	UnrealHeaderTool \
	UnrealInsights-Linux-Debug  \
	UnrealInsights-Linux-DebugGame  \
	UnrealInsights-Linux-Test  \
	UnrealInsights-Linux-Shipping  \
	UnrealInsights \
	UnrealLightmass-Linux-Debug  \
	UnrealLightmass-Linux-DebugGame  \
	UnrealLightmass-Linux-Test  \
	UnrealLightmass-Linux-Shipping  \
	UnrealLightmass \
	UnrealMultiUserServer-Linux-Debug  \
	UnrealMultiUserServer-Linux-DebugGame  \
	UnrealMultiUserServer-Linux-Test  \
	UnrealMultiUserServer-Linux-Shipping  \
	UnrealMultiUserServer \
	UnrealMultiUserSlateServer-Linux-Debug  \
	UnrealMultiUserSlateServer-Linux-DebugGame  \
	UnrealMultiUserSlateServer-Linux-Test  \
	UnrealMultiUserSlateServer-Linux-Shipping  \
	UnrealMultiUserSlateServer \
	UnrealObjectPtrTool-Linux-Debug  \
	UnrealObjectPtrTool-Linux-DebugGame  \
	UnrealObjectPtrTool-Linux-Test  \
	UnrealObjectPtrTool-Linux-Shipping  \
	UnrealObjectPtrTool \
	UnrealPackageTool-Linux-Debug  \
	UnrealPackageTool-Linux-DebugGame  \
	UnrealPackageTool-Linux-Test  \
	UnrealPackageTool-Linux-Shipping  \
	UnrealPackageTool \
	UnrealPak-Linux-Debug  \
	UnrealPak-Linux-DebugGame  \
	UnrealPak-Linux-Test  \
	UnrealPak-Linux-Shipping  \
	UnrealPak \
	UnrealRecoverySvc-Linux-Debug  \
	UnrealRecoverySvc-Linux-DebugGame  \
	UnrealRecoverySvc-Linux-Test  \
	UnrealRecoverySvc-Linux-Shipping  \
	UnrealRecoverySvc \
	UnrealVersionSelector-Linux-Debug  \
	UnrealVersionSelector-Linux-DebugGame  \
	UnrealVersionSelector-Linux-Test  \
	UnrealVersionSelector-Linux-Shipping  \
	UnrealVersionSelector \
	UnrealVirtualizationTool-Linux-Debug  \
	UnrealVirtualizationTool-Linux-DebugGame  \
	UnrealVirtualizationTool-Linux-Test  \
	UnrealVirtualizationTool-Linux-Shipping  \
	UnrealVirtualizationTool \
	Unsync-Linux-Debug  \
	Unsync-Linux-DebugGame  \
	Unsync-Linux-Test  \
	Unsync-Linux-Shipping  \
	Unsync \
	TextureShareSDK-Linux-Debug  \
	TextureShareSDK-Linux-DebugGame  \
	TextureShareSDK-Linux-Test  \
	TextureShareSDK-Linux-Shipping  \
	TextureShareSDK \
	BootstrapPackagedGame-Linux-Debug  \
	BootstrapPackagedGame-Linux-DebugGame  \
	BootstrapPackagedGame-Linux-Test  \
	BootstrapPackagedGame-Linux-Shipping  \
	BootstrapPackagedGame \
	ZenDashboard-Linux-Debug  \
	ZenDashboard-Linux-DebugGame  \
	ZenDashboard-Linux-Test  \
	ZenDashboard-Linux-Shipping  \
	ZenDashboard \
	UnrealClient-Linux-Debug  \
	UnrealClient-Linux-DebugGame  \
	UnrealClient-Linux-Test  \
	UnrealClient-Linux-Shipping  \
	UnrealClient \
	UnrealEditor-Linux-Debug  \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Test  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-Debug  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Test  \
	UnrealGame-Linux-Shipping  \
	UnrealGame \
	UnrealServer-Linux-Debug  \
	UnrealServer-Linux-DebugGame  \
	UnrealServer-Linux-Test  \
	UnrealServer-Linux-Shipping  \
	UnrealServer\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend KitchenSinkEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug KitchenSinkEditor-Linux-Debug


KitchenSink-Linux-Debug:
	 $(PROJECTBUILD) KitchenSink Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

KitchenSink-Linux-DebugGame:
	 $(PROJECTBUILD) KitchenSink Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

KitchenSink-Linux-Test:
	 $(PROJECTBUILD) KitchenSink Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

KitchenSink-Linux-Shipping:
	 $(PROJECTBUILD) KitchenSink Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

KitchenSink:
	 $(PROJECTBUILD) KitchenSink Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

KitchenSinkEditor-Linux-Debug:
	 $(PROJECTBUILD) KitchenSinkEditor Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

KitchenSinkEditor-Linux-DebugGame:
	 $(PROJECTBUILD) KitchenSinkEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

KitchenSinkEditor-Linux-Test:
	 $(PROJECTBUILD) KitchenSinkEditor Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

KitchenSinkEditor-Linux-Shipping:
	 $(PROJECTBUILD) KitchenSinkEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

KitchenSinkEditor:
	 $(PROJECTBUILD) KitchenSinkEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

BaseTextureBuildWorker-Linux-Debug:
	 $(BUILD) BaseTextureBuildWorker Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

BaseTextureBuildWorker-Linux-DebugGame:
	 $(BUILD) BaseTextureBuildWorker Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

BaseTextureBuildWorker-Linux-Test:
	 $(BUILD) BaseTextureBuildWorker Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

BaseTextureBuildWorker-Linux-Shipping:
	 $(BUILD) BaseTextureBuildWorker Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

BaseTextureBuildWorker:
	 $(BUILD) BaseTextureBuildWorker Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

BenchmarkTool-Linux-Debug:
	 $(BUILD) BenchmarkTool Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

BenchmarkTool-Linux-DebugGame:
	 $(BUILD) BenchmarkTool Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

BenchmarkTool-Linux-Test:
	 $(BUILD) BenchmarkTool Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

BenchmarkTool-Linux-Shipping:
	 $(BUILD) BenchmarkTool Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

BenchmarkTool:
	 $(BUILD) BenchmarkTool Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

BlankProgram-Linux-Debug:
	 $(BUILD) BlankProgram Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

BlankProgram-Linux-DebugGame:
	 $(BUILD) BlankProgram Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

BlankProgram-Linux-Test:
	 $(BUILD) BlankProgram Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

BlankProgram-Linux-Shipping:
	 $(BUILD) BlankProgram Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

BlankProgram:
	 $(BUILD) BlankProgram Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

BuildPatchTool-Linux-Debug:
	 $(BUILD) BuildPatchTool Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

BuildPatchTool-Linux-DebugGame:
	 $(BUILD) BuildPatchTool Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

BuildPatchTool-Linux-Test:
	 $(BUILD) BuildPatchTool Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

BuildPatchTool-Linux-Shipping:
	 $(BUILD) BuildPatchTool Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

BuildPatchTool:
	 $(BUILD) BuildPatchTool Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

ChaosUserDataPTTests-Linux-Debug:
	 $(BUILD) ChaosUserDataPTTests Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

ChaosUserDataPTTests-Linux-DebugGame:
	 $(BUILD) ChaosUserDataPTTests Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

ChaosUserDataPTTests-Linux-Test:
	 $(BUILD) ChaosUserDataPTTests Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

ChaosUserDataPTTests-Linux-Shipping:
	 $(BUILD) ChaosUserDataPTTests Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

ChaosUserDataPTTests:
	 $(BUILD) ChaosUserDataPTTests Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

ChaosVisualDebugger-Linux-Debug:
	 $(BUILD) ChaosVisualDebugger Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

ChaosVisualDebugger-Linux-DebugGame:
	 $(BUILD) ChaosVisualDebugger Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

ChaosVisualDebugger-Linux-Test:
	 $(BUILD) ChaosVisualDebugger Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

ChaosVisualDebugger-Linux-Shipping:
	 $(BUILD) ChaosVisualDebugger Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

ChaosVisualDebugger:
	 $(BUILD) ChaosVisualDebugger Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

CrashReportClient-Linux-Debug:
	 $(BUILD) CrashReportClient Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

CrashReportClient-Linux-DebugGame:
	 $(BUILD) CrashReportClient Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

CrashReportClient-Linux-Test:
	 $(BUILD) CrashReportClient Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

CrashReportClient-Linux-Shipping:
	 $(BUILD) CrashReportClient Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

CrashReportClient:
	 $(BUILD) CrashReportClient Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

CrashReportClientEditor-Linux-Debug:
	 $(BUILD) CrashReportClientEditor Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

CrashReportClientEditor-Linux-DebugGame:
	 $(BUILD) CrashReportClientEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

CrashReportClientEditor-Linux-Test:
	 $(BUILD) CrashReportClientEditor Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

CrashReportClientEditor-Linux-Shipping:
	 $(BUILD) CrashReportClientEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

CrashReportClientEditor:
	 $(BUILD) CrashReportClientEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithUE4ArchiCAD-Linux-Debug:
	 $(BUILD) DatasmithUE4ArchiCAD Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithUE4ArchiCAD-Linux-DebugGame:
	 $(BUILD) DatasmithUE4ArchiCAD Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithUE4ArchiCAD-Linux-Test:
	 $(BUILD) DatasmithUE4ArchiCAD Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithUE4ArchiCAD-Linux-Shipping:
	 $(BUILD) DatasmithUE4ArchiCAD Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithUE4ArchiCAD:
	 $(BUILD) DatasmithUE4ArchiCAD Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithArchiCAD-Linux-Debug:
	 $(BUILD) DatasmithArchiCAD Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithArchiCAD-Linux-DebugGame:
	 $(BUILD) DatasmithArchiCAD Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithArchiCAD-Linux-Test:
	 $(BUILD) DatasmithArchiCAD Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithArchiCAD-Linux-Shipping:
	 $(BUILD) DatasmithArchiCAD Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithArchiCAD:
	 $(BUILD) DatasmithArchiCAD Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithCADWorker-Linux-Debug:
	 $(BUILD) DatasmithCADWorker Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithCADWorker-Linux-DebugGame:
	 $(BUILD) DatasmithCADWorker Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithCADWorker-Linux-Test:
	 $(BUILD) DatasmithCADWorker Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithCADWorker-Linux-Shipping:
	 $(BUILD) DatasmithCADWorker Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithCADWorker:
	 $(BUILD) DatasmithCADWorker Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithFacadeCSharp-Linux-Debug:
	 $(BUILD) DatasmithFacadeCSharp Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithFacadeCSharp-Linux-DebugGame:
	 $(BUILD) DatasmithFacadeCSharp Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithFacadeCSharp-Linux-Test:
	 $(BUILD) DatasmithFacadeCSharp Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithFacadeCSharp-Linux-Shipping:
	 $(BUILD) DatasmithFacadeCSharp Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithFacadeCSharp:
	 $(BUILD) DatasmithFacadeCSharp Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2016-Linux-Debug:
	 $(BUILD) DatasmithMax2016 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2016-Linux-DebugGame:
	 $(BUILD) DatasmithMax2016 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2016-Linux-Test:
	 $(BUILD) DatasmithMax2016 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2016-Linux-Shipping:
	 $(BUILD) DatasmithMax2016 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2016:
	 $(BUILD) DatasmithMax2016 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2017-Linux-Debug:
	 $(BUILD) DatasmithMax2017 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2017-Linux-DebugGame:
	 $(BUILD) DatasmithMax2017 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2017-Linux-Test:
	 $(BUILD) DatasmithMax2017 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2017-Linux-Shipping:
	 $(BUILD) DatasmithMax2017 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2017:
	 $(BUILD) DatasmithMax2017 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2018-Linux-Debug:
	 $(BUILD) DatasmithMax2018 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2018-Linux-DebugGame:
	 $(BUILD) DatasmithMax2018 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2018-Linux-Test:
	 $(BUILD) DatasmithMax2018 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2018-Linux-Shipping:
	 $(BUILD) DatasmithMax2018 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2018:
	 $(BUILD) DatasmithMax2018 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2019-Linux-Debug:
	 $(BUILD) DatasmithMax2019 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2019-Linux-DebugGame:
	 $(BUILD) DatasmithMax2019 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2019-Linux-Test:
	 $(BUILD) DatasmithMax2019 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2019-Linux-Shipping:
	 $(BUILD) DatasmithMax2019 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2019:
	 $(BUILD) DatasmithMax2019 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2020-Linux-Debug:
	 $(BUILD) DatasmithMax2020 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2020-Linux-DebugGame:
	 $(BUILD) DatasmithMax2020 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2020-Linux-Test:
	 $(BUILD) DatasmithMax2020 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2020-Linux-Shipping:
	 $(BUILD) DatasmithMax2020 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2020:
	 $(BUILD) DatasmithMax2020 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2021-Linux-Debug:
	 $(BUILD) DatasmithMax2021 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2021-Linux-DebugGame:
	 $(BUILD) DatasmithMax2021 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2021-Linux-Test:
	 $(BUILD) DatasmithMax2021 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2021-Linux-Shipping:
	 $(BUILD) DatasmithMax2021 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2021:
	 $(BUILD) DatasmithMax2021 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2022-Linux-Debug:
	 $(BUILD) DatasmithMax2022 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2022-Linux-DebugGame:
	 $(BUILD) DatasmithMax2022 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2022-Linux-Test:
	 $(BUILD) DatasmithMax2022 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2022-Linux-Shipping:
	 $(BUILD) DatasmithMax2022 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2022:
	 $(BUILD) DatasmithMax2022 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2023-Linux-Debug:
	 $(BUILD) DatasmithMax2023 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2023-Linux-DebugGame:
	 $(BUILD) DatasmithMax2023 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2023-Linux-Test:
	 $(BUILD) DatasmithMax2023 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2023-Linux-Shipping:
	 $(BUILD) DatasmithMax2023 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithMax2023:
	 $(BUILD) DatasmithMax2023 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2019-Linux-Debug:
	 $(BUILD) DatasmithNavisworks2019 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2019-Linux-DebugGame:
	 $(BUILD) DatasmithNavisworks2019 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2019-Linux-Test:
	 $(BUILD) DatasmithNavisworks2019 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2019-Linux-Shipping:
	 $(BUILD) DatasmithNavisworks2019 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2019:
	 $(BUILD) DatasmithNavisworks2019 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2020-Linux-Debug:
	 $(BUILD) DatasmithNavisworks2020 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2020-Linux-DebugGame:
	 $(BUILD) DatasmithNavisworks2020 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2020-Linux-Test:
	 $(BUILD) DatasmithNavisworks2020 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2020-Linux-Shipping:
	 $(BUILD) DatasmithNavisworks2020 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2020:
	 $(BUILD) DatasmithNavisworks2020 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2021-Linux-Debug:
	 $(BUILD) DatasmithNavisworks2021 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2021-Linux-DebugGame:
	 $(BUILD) DatasmithNavisworks2021 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2021-Linux-Test:
	 $(BUILD) DatasmithNavisworks2021 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2021-Linux-Shipping:
	 $(BUILD) DatasmithNavisworks2021 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2021:
	 $(BUILD) DatasmithNavisworks2021 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2022-Linux-Debug:
	 $(BUILD) DatasmithNavisworks2022 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2022-Linux-DebugGame:
	 $(BUILD) DatasmithNavisworks2022 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2022-Linux-Test:
	 $(BUILD) DatasmithNavisworks2022 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2022-Linux-Shipping:
	 $(BUILD) DatasmithNavisworks2022 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2022:
	 $(BUILD) DatasmithNavisworks2022 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2023-Linux-Debug:
	 $(BUILD) DatasmithNavisworks2023 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2023-Linux-DebugGame:
	 $(BUILD) DatasmithNavisworks2023 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2023-Linux-Test:
	 $(BUILD) DatasmithNavisworks2023 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2023-Linux-Shipping:
	 $(BUILD) DatasmithNavisworks2023 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithNavisworks2023:
	 $(BUILD) DatasmithNavisworks2023 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2018-Linux-Debug:
	 $(BUILD) DatasmithRevit2018 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2018-Linux-DebugGame:
	 $(BUILD) DatasmithRevit2018 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2018-Linux-Test:
	 $(BUILD) DatasmithRevit2018 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2018-Linux-Shipping:
	 $(BUILD) DatasmithRevit2018 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2018:
	 $(BUILD) DatasmithRevit2018 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2019-Linux-Debug:
	 $(BUILD) DatasmithRevit2019 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2019-Linux-DebugGame:
	 $(BUILD) DatasmithRevit2019 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2019-Linux-Test:
	 $(BUILD) DatasmithRevit2019 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2019-Linux-Shipping:
	 $(BUILD) DatasmithRevit2019 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2019:
	 $(BUILD) DatasmithRevit2019 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2020-Linux-Debug:
	 $(BUILD) DatasmithRevit2020 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2020-Linux-DebugGame:
	 $(BUILD) DatasmithRevit2020 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2020-Linux-Test:
	 $(BUILD) DatasmithRevit2020 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2020-Linux-Shipping:
	 $(BUILD) DatasmithRevit2020 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2020:
	 $(BUILD) DatasmithRevit2020 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2021-Linux-Debug:
	 $(BUILD) DatasmithRevit2021 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2021-Linux-DebugGame:
	 $(BUILD) DatasmithRevit2021 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2021-Linux-Test:
	 $(BUILD) DatasmithRevit2021 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2021-Linux-Shipping:
	 $(BUILD) DatasmithRevit2021 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2021:
	 $(BUILD) DatasmithRevit2021 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2022-Linux-Debug:
	 $(BUILD) DatasmithRevit2022 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2022-Linux-DebugGame:
	 $(BUILD) DatasmithRevit2022 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2022-Linux-Test:
	 $(BUILD) DatasmithRevit2022 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2022-Linux-Shipping:
	 $(BUILD) DatasmithRevit2022 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2022:
	 $(BUILD) DatasmithRevit2022 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2023-Linux-Debug:
	 $(BUILD) DatasmithRevit2023 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2023-Linux-DebugGame:
	 $(BUILD) DatasmithRevit2023 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2023-Linux-Test:
	 $(BUILD) DatasmithRevit2023 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2023-Linux-Shipping:
	 $(BUILD) DatasmithRevit2023 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRevit2023:
	 $(BUILD) DatasmithRevit2023 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRhino6-Linux-Debug:
	 $(BUILD) DatasmithRhino6 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRhino6-Linux-DebugGame:
	 $(BUILD) DatasmithRhino6 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRhino6-Linux-Test:
	 $(BUILD) DatasmithRhino6 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRhino6-Linux-Shipping:
	 $(BUILD) DatasmithRhino6 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRhino6:
	 $(BUILD) DatasmithRhino6 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRhino7-Linux-Debug:
	 $(BUILD) DatasmithRhino7 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRhino7-Linux-DebugGame:
	 $(BUILD) DatasmithRhino7 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRhino7-Linux-Test:
	 $(BUILD) DatasmithRhino7 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRhino7-Linux-Shipping:
	 $(BUILD) DatasmithRhino7 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithRhino7:
	 $(BUILD) DatasmithRhino7 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSDK-Linux-Debug:
	 $(BUILD) DatasmithSDK Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSDK-Linux-DebugGame:
	 $(BUILD) DatasmithSDK Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSDK-Linux-Test:
	 $(BUILD) DatasmithSDK Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSDK-Linux-Shipping:
	 $(BUILD) DatasmithSDK Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSDK:
	 $(BUILD) DatasmithSDK Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2019-Linux-Debug:
	 $(BUILD) DatasmithSketchUpRuby2019 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2019-Linux-DebugGame:
	 $(BUILD) DatasmithSketchUpRuby2019 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2019-Linux-Test:
	 $(BUILD) DatasmithSketchUpRuby2019 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2019-Linux-Shipping:
	 $(BUILD) DatasmithSketchUpRuby2019 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2019:
	 $(BUILD) DatasmithSketchUpRuby2019 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2020-Linux-Debug:
	 $(BUILD) DatasmithSketchUpRuby2020 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2020-Linux-DebugGame:
	 $(BUILD) DatasmithSketchUpRuby2020 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2020-Linux-Test:
	 $(BUILD) DatasmithSketchUpRuby2020 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2020-Linux-Shipping:
	 $(BUILD) DatasmithSketchUpRuby2020 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2020:
	 $(BUILD) DatasmithSketchUpRuby2020 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2021-Linux-Debug:
	 $(BUILD) DatasmithSketchUpRuby2021 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2021-Linux-DebugGame:
	 $(BUILD) DatasmithSketchUpRuby2021 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2021-Linux-Test:
	 $(BUILD) DatasmithSketchUpRuby2021 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2021-Linux-Shipping:
	 $(BUILD) DatasmithSketchUpRuby2021 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2021:
	 $(BUILD) DatasmithSketchUpRuby2021 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2022-Linux-Debug:
	 $(BUILD) DatasmithSketchUpRuby2022 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2022-Linux-DebugGame:
	 $(BUILD) DatasmithSketchUpRuby2022 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2022-Linux-Test:
	 $(BUILD) DatasmithSketchUpRuby2022 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2022-Linux-Shipping:
	 $(BUILD) DatasmithSketchUpRuby2022 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSketchUpRuby2022:
	 $(BUILD) DatasmithSketchUpRuby2022 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSolidworks2021-Linux-Debug:
	 $(BUILD) DatasmithSolidworks2021 Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSolidworks2021-Linux-DebugGame:
	 $(BUILD) DatasmithSolidworks2021 Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSolidworks2021-Linux-Test:
	 $(BUILD) DatasmithSolidworks2021 Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSolidworks2021-Linux-Shipping:
	 $(BUILD) DatasmithSolidworks2021 Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DatasmithSolidworks2021:
	 $(BUILD) DatasmithSolidworks2021 Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

EpicWebHelper-Linux-Debug:
	 $(BUILD) EpicWebHelper Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

EpicWebHelper-Linux-DebugGame:
	 $(BUILD) EpicWebHelper Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

EpicWebHelper-Linux-Test:
	 $(BUILD) EpicWebHelper Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

EpicWebHelper-Linux-Shipping:
	 $(BUILD) EpicWebHelper Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

EpicWebHelper:
	 $(BUILD) EpicWebHelper Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

HeadlessChaos-Linux-Debug:
	 $(BUILD) HeadlessChaos Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

HeadlessChaos-Linux-DebugGame:
	 $(BUILD) HeadlessChaos Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

HeadlessChaos-Linux-Test:
	 $(BUILD) HeadlessChaos Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

HeadlessChaos-Linux-Shipping:
	 $(BUILD) HeadlessChaos Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

HeadlessChaos:
	 $(BUILD) HeadlessChaos Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

HeadlessChaosPerf-Linux-Debug:
	 $(BUILD) HeadlessChaosPerf Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

HeadlessChaosPerf-Linux-DebugGame:
	 $(BUILD) HeadlessChaosPerf Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

HeadlessChaosPerf-Linux-Test:
	 $(BUILD) HeadlessChaosPerf Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

HeadlessChaosPerf-Linux-Shipping:
	 $(BUILD) HeadlessChaosPerf Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

HeadlessChaosPerf:
	 $(BUILD) HeadlessChaosPerf Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

InterchangeWorker-Linux-Debug:
	 $(BUILD) InterchangeWorker Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

InterchangeWorker-Linux-DebugGame:
	 $(BUILD) InterchangeWorker Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

InterchangeWorker-Linux-Test:
	 $(BUILD) InterchangeWorker Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

InterchangeWorker-Linux-Shipping:
	 $(BUILD) InterchangeWorker Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

InterchangeWorker:
	 $(BUILD) InterchangeWorker Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

LiveCodingConsole-Linux-Debug:
	 $(BUILD) LiveCodingConsole Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

LiveCodingConsole-Linux-DebugGame:
	 $(BUILD) LiveCodingConsole Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

LiveCodingConsole-Linux-Test:
	 $(BUILD) LiveCodingConsole Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

LiveCodingConsole-Linux-Shipping:
	 $(BUILD) LiveCodingConsole Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

LiveCodingConsole:
	 $(BUILD) LiveCodingConsole Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

LowLevelTests-Linux-Debug:
	 $(BUILD) LowLevelTests Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

LowLevelTests-Linux-DebugGame:
	 $(BUILD) LowLevelTests Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

LowLevelTests-Linux-Test:
	 $(BUILD) LowLevelTests Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

LowLevelTests-Linux-Shipping:
	 $(BUILD) LowLevelTests Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

LowLevelTests:
	 $(BUILD) LowLevelTests Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

ReplicationSystemTest-Linux-Debug:
	 $(BUILD) ReplicationSystemTest Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

ReplicationSystemTest-Linux-DebugGame:
	 $(BUILD) ReplicationSystemTest Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

ReplicationSystemTest-Linux-Test:
	 $(BUILD) ReplicationSystemTest Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

ReplicationSystemTest-Linux-Shipping:
	 $(BUILD) ReplicationSystemTest Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

ReplicationSystemTest:
	 $(BUILD) ReplicationSystemTest Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

ShaderCompileWorker-Linux-Debug:
	 $(BUILD) ShaderCompileWorker Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

ShaderCompileWorker-Linux-DebugGame:
	 $(BUILD) ShaderCompileWorker Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

ShaderCompileWorker-Linux-Test:
	 $(BUILD) ShaderCompileWorker Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

ShaderCompileWorker-Linux-Shipping:
	 $(BUILD) ShaderCompileWorker Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

ShaderCompileWorker:
	 $(BUILD) ShaderCompileWorker Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DotNetPerforceLib-Linux-Debug:
	 $(BUILD) DotNetPerforceLib Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

DotNetPerforceLib-Linux-DebugGame:
	 $(BUILD) DotNetPerforceLib Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DotNetPerforceLib-Linux-Test:
	 $(BUILD) DotNetPerforceLib Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

DotNetPerforceLib-Linux-Shipping:
	 $(BUILD) DotNetPerforceLib Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DotNetPerforceLib:
	 $(BUILD) DotNetPerforceLib Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

SlateUGS-Linux-Debug:
	 $(BUILD) SlateUGS Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

SlateUGS-Linux-DebugGame:
	 $(BUILD) SlateUGS Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

SlateUGS-Linux-Test:
	 $(BUILD) SlateUGS Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

SlateUGS-Linux-Shipping:
	 $(BUILD) SlateUGS Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

SlateUGS:
	 $(BUILD) SlateUGS Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

SlateViewer-Linux-Debug:
	 $(BUILD) SlateViewer Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

SlateViewer-Linux-DebugGame:
	 $(BUILD) SlateViewer Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

SlateViewer-Linux-Test:
	 $(BUILD) SlateViewer Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

SlateViewer-Linux-Shipping:
	 $(BUILD) SlateViewer Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

SlateViewer:
	 $(BUILD) SlateViewer Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

SwitchboardListener-Linux-Debug:
	 $(BUILD) SwitchboardListener Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

SwitchboardListener-Linux-DebugGame:
	 $(BUILD) SwitchboardListener Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

SwitchboardListener-Linux-Test:
	 $(BUILD) SwitchboardListener Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

SwitchboardListener-Linux-Shipping:
	 $(BUILD) SwitchboardListener Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

SwitchboardListener:
	 $(BUILD) SwitchboardListener Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

SymsLibDump-Linux-Debug:
	 $(BUILD) SymsLibDump Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

SymsLibDump-Linux-DebugGame:
	 $(BUILD) SymsLibDump Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

SymsLibDump-Linux-Test:
	 $(BUILD) SymsLibDump Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

SymsLibDump-Linux-Shipping:
	 $(BUILD) SymsLibDump Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

SymsLibDump:
	 $(BUILD) SymsLibDump Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

TestPAL-Linux-Debug:
	 $(BUILD) TestPAL Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

TestPAL-Linux-DebugGame:
	 $(BUILD) TestPAL Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

TestPAL-Linux-Test:
	 $(BUILD) TestPAL Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

TestPAL-Linux-Shipping:
	 $(BUILD) TestPAL Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

TestPAL:
	 $(BUILD) TestPAL Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealFrontend-Linux-Debug:
	 $(BUILD) UnrealFrontend Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealFrontend-Linux-DebugGame:
	 $(BUILD) UnrealFrontend Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealFrontend-Linux-Test:
	 $(BUILD) UnrealFrontend Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealFrontend-Linux-Shipping:
	 $(BUILD) UnrealFrontend Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealFrontend:
	 $(BUILD) UnrealFrontend Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealHeaderTool-Linux-Debug:
	 $(BUILD) UnrealHeaderTool Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealHeaderTool-Linux-DebugGame:
	 $(BUILD) UnrealHeaderTool Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealHeaderTool-Linux-Test:
	 $(BUILD) UnrealHeaderTool Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealHeaderTool-Linux-Shipping:
	 $(BUILD) UnrealHeaderTool Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealHeaderTool:
	 $(BUILD) UnrealHeaderTool Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealInsights-Linux-Debug:
	 $(BUILD) UnrealInsights Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealInsights-Linux-DebugGame:
	 $(BUILD) UnrealInsights Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealInsights-Linux-Test:
	 $(BUILD) UnrealInsights Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealInsights-Linux-Shipping:
	 $(BUILD) UnrealInsights Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealInsights:
	 $(BUILD) UnrealInsights Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealLightmass-Linux-Debug:
	 $(BUILD) UnrealLightmass Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealLightmass-Linux-DebugGame:
	 $(BUILD) UnrealLightmass Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealLightmass-Linux-Test:
	 $(BUILD) UnrealLightmass Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealLightmass-Linux-Shipping:
	 $(BUILD) UnrealLightmass Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealLightmass:
	 $(BUILD) UnrealLightmass Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealMultiUserServer-Linux-Debug:
	 $(BUILD) UnrealMultiUserServer Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealMultiUserServer-Linux-DebugGame:
	 $(BUILD) UnrealMultiUserServer Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealMultiUserServer-Linux-Test:
	 $(BUILD) UnrealMultiUserServer Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealMultiUserServer-Linux-Shipping:
	 $(BUILD) UnrealMultiUserServer Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealMultiUserServer:
	 $(BUILD) UnrealMultiUserServer Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealMultiUserSlateServer-Linux-Debug:
	 $(BUILD) UnrealMultiUserSlateServer Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealMultiUserSlateServer-Linux-DebugGame:
	 $(BUILD) UnrealMultiUserSlateServer Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealMultiUserSlateServer-Linux-Test:
	 $(BUILD) UnrealMultiUserSlateServer Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealMultiUserSlateServer-Linux-Shipping:
	 $(BUILD) UnrealMultiUserSlateServer Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealMultiUserSlateServer:
	 $(BUILD) UnrealMultiUserSlateServer Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealObjectPtrTool-Linux-Debug:
	 $(BUILD) UnrealObjectPtrTool Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealObjectPtrTool-Linux-DebugGame:
	 $(BUILD) UnrealObjectPtrTool Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealObjectPtrTool-Linux-Test:
	 $(BUILD) UnrealObjectPtrTool Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealObjectPtrTool-Linux-Shipping:
	 $(BUILD) UnrealObjectPtrTool Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealObjectPtrTool:
	 $(BUILD) UnrealObjectPtrTool Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealPackageTool-Linux-Debug:
	 $(BUILD) UnrealPackageTool Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealPackageTool-Linux-DebugGame:
	 $(BUILD) UnrealPackageTool Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealPackageTool-Linux-Test:
	 $(BUILD) UnrealPackageTool Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealPackageTool-Linux-Shipping:
	 $(BUILD) UnrealPackageTool Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealPackageTool:
	 $(BUILD) UnrealPackageTool Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealPak-Linux-Debug:
	 $(BUILD) UnrealPak Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealPak-Linux-DebugGame:
	 $(BUILD) UnrealPak Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealPak-Linux-Test:
	 $(BUILD) UnrealPak Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealPak-Linux-Shipping:
	 $(BUILD) UnrealPak Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealPak:
	 $(BUILD) UnrealPak Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealRecoverySvc-Linux-Debug:
	 $(BUILD) UnrealRecoverySvc Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealRecoverySvc-Linux-DebugGame:
	 $(BUILD) UnrealRecoverySvc Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealRecoverySvc-Linux-Test:
	 $(BUILD) UnrealRecoverySvc Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealRecoverySvc-Linux-Shipping:
	 $(BUILD) UnrealRecoverySvc Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealRecoverySvc:
	 $(BUILD) UnrealRecoverySvc Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealVersionSelector-Linux-Debug:
	 $(BUILD) UnrealVersionSelector Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealVersionSelector-Linux-DebugGame:
	 $(BUILD) UnrealVersionSelector Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealVersionSelector-Linux-Test:
	 $(BUILD) UnrealVersionSelector Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealVersionSelector-Linux-Shipping:
	 $(BUILD) UnrealVersionSelector Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealVersionSelector:
	 $(BUILD) UnrealVersionSelector Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealVirtualizationTool-Linux-Debug:
	 $(BUILD) UnrealVirtualizationTool Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealVirtualizationTool-Linux-DebugGame:
	 $(BUILD) UnrealVirtualizationTool Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealVirtualizationTool-Linux-Test:
	 $(BUILD) UnrealVirtualizationTool Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealVirtualizationTool-Linux-Shipping:
	 $(BUILD) UnrealVirtualizationTool Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealVirtualizationTool:
	 $(BUILD) UnrealVirtualizationTool Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

Unsync-Linux-Debug:
	 $(BUILD) Unsync Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

Unsync-Linux-DebugGame:
	 $(BUILD) Unsync Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

Unsync-Linux-Test:
	 $(BUILD) Unsync Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

Unsync-Linux-Shipping:
	 $(BUILD) Unsync Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

Unsync:
	 $(BUILD) Unsync Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

TextureShareSDK-Linux-Debug:
	 $(BUILD) TextureShareSDK Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

TextureShareSDK-Linux-DebugGame:
	 $(BUILD) TextureShareSDK Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

TextureShareSDK-Linux-Test:
	 $(BUILD) TextureShareSDK Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

TextureShareSDK-Linux-Shipping:
	 $(BUILD) TextureShareSDK Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

TextureShareSDK:
	 $(BUILD) TextureShareSDK Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

BootstrapPackagedGame-Linux-Debug:
	 $(BUILD) BootstrapPackagedGame Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

BootstrapPackagedGame-Linux-DebugGame:
	 $(BUILD) BootstrapPackagedGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

BootstrapPackagedGame-Linux-Test:
	 $(BUILD) BootstrapPackagedGame Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

BootstrapPackagedGame-Linux-Shipping:
	 $(BUILD) BootstrapPackagedGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

BootstrapPackagedGame:
	 $(BUILD) BootstrapPackagedGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

ZenDashboard-Linux-Debug:
	 $(BUILD) ZenDashboard Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

ZenDashboard-Linux-DebugGame:
	 $(BUILD) ZenDashboard Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

ZenDashboard-Linux-Test:
	 $(BUILD) ZenDashboard Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

ZenDashboard-Linux-Shipping:
	 $(BUILD) ZenDashboard Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

ZenDashboard:
	 $(BUILD) ZenDashboard Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealClient-Linux-Debug:
	 $(BUILD) UnrealClient Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealClient-Linux-DebugGame:
	 $(BUILD) UnrealClient Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealClient-Linux-Test:
	 $(BUILD) UnrealClient Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealClient-Linux-Shipping:
	 $(BUILD) UnrealClient Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealClient:
	 $(BUILD) UnrealClient Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Debug:
	 $(BUILD) UnrealEditor Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Test:
	 $(BUILD) UnrealEditor Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Debug:
	 $(BUILD) UnrealGame Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Test:
	 $(BUILD) UnrealGame Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealServer-Linux-Debug:
	 $(BUILD) UnrealServer Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealServer-Linux-DebugGame:
	 $(BUILD) UnrealServer Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealServer-Linux-Test:
	 $(BUILD) UnrealServer Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealServer-Linux-Shipping:
	 $(BUILD) UnrealServer Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealServer:
	 $(BUILD) UnrealServer Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
