#include <array>
#include <iostream>
#include <random>

auto main() -> int
{
  std::array games = {"1 HP",
                      "1 minute to prepare",
                      "1 vs 100",
                      "3 Rules",
                      "A Hard to Let Go Feeling",
                      "A Small World",
                      "A World in the Skies",
                      "A light in the dark",
                      "A single resource",
                      "Absorb your enemies",
                      "An abandoned world",
                      "Astral Plane",
                      "At the beginning there is nothing",
                      "Automation",
                      "Bouncy World",
                      "Break the cycle",
                      "Broken world",
                      "Butterfly Effect",
                      "Chain Reaction",
                      "Change the genre of a classic video game",
                      "Clockwork",
                      "Color changes everything",
                      "Combine 2 incompatible genres (e.g. turn based racing)",
                      "Connections",
                      "Contagious",
                      "Contain it",
                      "Containment",
                      "Control the environment, not the player",
                      "Dark / Light",
                      "Darkness is your friend",
                      "Day and night",
                      "Death is not the end",
                      "Death is only the Beginning",
                      "Death is useful",
                      "Decay",
                      "Deeper and deeper",
                      "Delay the inevitable",
                      "Delivery",
                      "Different perspective",
                      "Don’t trust the game",
                      "Dreamland",
                      "Dreams",
                      "Duplication",
                      "Dying planet",
                      "Each playthrough builds on the last",
                      "Everything grows",
                      "Everything has a Price",
                      "Everything is Too Little",
                      "Everything is connected",
                      "Evolve",
                      "Evolve to survive",
                      "Expanding",
                      "Expansion",
                      "Factory",
                      "Feeding the monster",
                      "Floating islands",
                      "Fragile",
                      "Garden",
                      "Generations",
                      "Hidden world",
                      "Inconvenient Superpowers",
                      "Into the unknown",
                      "Island",
                      "Isolation",
                      "It only changes when you aren’t looking",
                      "It’s spreading",
                      "Janitors at a School for Wizards",
                      "Keep growing",
                      "Keep it alive",
                      "Layers",
                      "Leave something behind",
                      "Light is key",
                      "Limited memory",
                      "Limited space",
                      "Lost signal",
                      "Low Expectations",
                      "Low Tech",
                      "Machines",
                      "Magic, but at what cost?",
                      "Making connections",
                      "Microscopic Life",
                      "Momentum",
                      "Moving fortress",
                      "Mutation",
                      "Night is coming",
                      "Nightlife",
                      "No upgrades, only downgrades",
                      "Nomad",
                      "Nothing is permanent",
                      "On / Off",
                      "One Level, But Constantly Changing",
                      "One Tool, Many Uses",
                      "One enemy only",
                      "One item, many uses",
                      "One minute",
                      "One room",
                      "One time use",
                      "One tool, many uses",
                      "Online Dance Battle",
                      "Only 5 minutes",
                      "Only one enemy",
                      "Only three colors",
                      "Outdated technology",
                      "Parallel Dimensions",
                      "Parallel worlds",
                      "Parasite",
                      "Pausing has Consequences",
                      "Play with Food",
                      "Protect it",
                      "Ridiculously overpowered",
                      "Risky powerups",
                      "Ruins",
                      "Running out of space",
                      "Sacrifices must be made",
                      "Safe in the dark",
                      "Salvage and repair",
                      "Save yourself, not the world",
                      "Self-replication",
                      "Sensory Deprivation",
                      "Shipwrecked",
                      "Side effects",
                      "Signal lost",
                      "Simplicity",
                      "Small character, big enemies",
                      "Small world",
                      "Space exploration",
                      "Split in two",
                      "Start with nothing",
                      "Stuck in a loop",
                      "Summoning",
                      "Take one, leave one",
                      "Take one, leave the rest",
                      "The 90s",
                      "The Robot Uprising",
                      "The Zodiac",
                      "The environment changes you",
                      "The more you have, the worse it is",
                      "The world changes when you are not looking",
                      "They Are Listening To Us",
                      "Tiny machines",
                      "Tiny town",
                      "Turn a violent genre non-violent",
                      "Two Colors",
                      "Two connected worlds",
                      "Two points of view",
                      "Unconventional travel",
                      "Underground",
                      "Unusual magic",
                      "Upgrade yourself",
                      "Wait, Are We The Bad Guys?",
                      "World of Waves",
                      "You Control The Environment, Not The Character",
                      "You are Alone",
                      "You are not the main character",
                      "You are the final boss",
                      "You are the power source",
                      "You are the weapon",
                      "You are what you eat",
                      "You can’t save them all",
                      "You control the environment, not player",
                      "You control the scenario, not the character",
                      "You really shouldn’t mix those",
                      "Your life is currency"};

  std::random_device rd;
  std::mt19937 gen(rd());
  std::uniform_int_distribution<> dis(0, games.size() - 1);

  int randomIndex = dis(gen);
  std::cout << "Random game: " << games[randomIndex] << std::endl;
}
