#pragma once

#include "ue.patch"
#include <AIController.h>
#include <Animation/AnimInstance.h>
#include <Animation/AnimMontage.h>
#include <Animation/AnimSequence.h>
#include <Animation/AnimationAsset.h>
#include <Animation/SkeletalMeshActor.h>
#include <Blueprint/AIBlueprintHelperLibrary.h>
#include <Blueprint/UserWidget.h>
#include <Components/ActorComponent.h>
#include <Components/AudioComponent.h>
#include <Components/BoxComponent.h>
#include <Components/Button.h>
#include <Components/CanvasPanel.h>
#include <Components/CapsuleComponent.h>
#include <Components/CheckBox.h>
#include <Components/DirectionalLightComponent.h>
#include <Components/Image.h>
#include <Components/InstancedStaticMeshComponent.h>
#include <Components/ListView.h>
#include <Components/Overlay.h>
#include <Components/PointLightComponent.h>
#include <Components/ProgressBar.h>
#include <Components/SceneComponent.h>
#include <Components/SkeletalMeshComponent.h>
#include <Components/SphereComponent.h>
#include <Components/SplineComponent.h>
#include <Components/SpotLightComponent.h>
#include <Components/StaticMeshComponent.h>
#include <Components/TextBlock.h>
#include <Components/TileView.h>
#include <Components/WidgetSwitcher.h>
#include <CoreMinimal.h>
#include <DrawDebugHelpers.h>
#include <Engine.h>
#include <Engine/PostProcessVolume.h>
#include <Engine/SkeletalMesh.h>
#include <Engine/SpotLight.h>
#include <Engine/StaticMesh.h>
#include <Engine/StaticMeshActor.h>
#include <Engine/World.h>
#include <EngineUtils.h>
#include <GameFramework/Actor.h>
#include <GameFramework/Character.h>
#include <GameFramework/CharacterMovementComponent.h>
#include <GameFramework/GameModeBase.h>
#include <GameFramework/GameStateBase.h>
#include <GameFramework/HUD.h>
#include <Hash/Blake3.h>
#include <Internationalization/Text.h>
#include <Kismet/GameplayStatics.h>
#include <Kismet/KismetSystemLibrary.h>
#include <Materials/MaterialInstance.h>
#include <Materials/MaterialInstanceConstant.h>
#include <Modules/ModuleManager.h>
#include <QofL/abbr.h>
#include <QofL/check_ret.h>
#include <QofL/class_finder.h>
#include <QofL/get_prop.h>
#include <QofL/loc.h>
#include <QofL/log.h>
#include <QofL/obj_finder.h>
#include <Slate/SlateBrushAsset.h>
#include <Sound/SoundBase.h>
#include <Sound/SoundCue.h>
#include <Sound/SoundWave.h>
#include <TimerManager.h>
#include <UObject/ConstructorHelpers.h>
#include <UObject/Object.h>
#include <algorithm>
#include <array>
#include <cassert>
#include <cmath>
#include <functional>
#include <iostream>
#include <map>
#include <memory>
#include <sstream>
#include <string>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
